# Generated by Django 4.1.5 on 2023-04-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ayurveda", "0002_alter_doctor_booking_appointment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor_booking",
            name="appointment_date",
            field=models.CharField(max_length=40),
        ),
    ]
