# Generated by Django 4.1.5 on 2023-04-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ayurveda", "0003_alter_doctor_booking_appointment_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor_booking",
            old_name="appointment_date",
            new_name="appointment_day",
        ),
    ]
