# Generated by Django 4.1.5 on 2023-04-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ayurveda", "0004_rename_appointment_date_doctor_booking_appointment_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="Remedy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disease", models.CharField(max_length=50)),
                ("symptoms", models.CharField(max_length=100)),
                ("remedy", models.CharField(max_length=100)),
                ("remedy_photo", models.ImageField(upload_to="images")),
                ("remedystatus", models.CharField(max_length=10)),
            ],
        ),
    ]
