# Generated by Django 4.1.5 on 2023-04-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ayurveda", "0005_remedy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remedy",
            name="remedy",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="remedy",
            name="symptoms",
            field=models.CharField(max_length=500),
        ),
    ]
