# Generated by Django 4.1.5 on 2023-04-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ayurveda", "0006_alter_remedy_remedy_alter_remedy_symptoms"),
    ]

    operations = [
        migrations.CreateModel(
            name="Packages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_name", models.CharField(max_length=50)),
                ("package_goal", models.CharField(max_length=500)),
                ("package_description", models.CharField(max_length=500)),
                ("package_duration", models.CharField(max_length=50)),
                ("package_price", models.CharField(max_length=50)),
                ("package_photo", models.ImageField(upload_to="images")),
                ("package_status", models.CharField(max_length=10)),
            ],
        ),
    ]
