# Generated by Django 4.1.5 on 2023-05-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ayurveda", "0012_complaints_replay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaints_replay",
            name="replay",
            field=models.CharField(default="No Replay", max_length=500),
        ),
    ]
