# Generated by Django 4.1.5 on 2023-05-01 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ayurveda", "0013_alter_complaints_replay_replay"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplaintsAndReplay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complaint", models.CharField(max_length=500)),
                ("date", models.DateField()),
                ("replay", models.CharField(default="No Replay", max_length=500)),
                ("complaint_status", models.CharField(max_length=10)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.patient",
                    ),
                ),
            ],
        ),
    ]
