# Generated by Django 4.1.5 on 2023-05-01 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ayurveda", "0014_complaintsandreplay"),
    ]

    operations = [
        migrations.CreateModel(
            name="Token_Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.CharField(max_length=40)),
                ("number", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("bookingstatus", models.CharField(max_length=10)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.patient",
                    ),
                ),
            ],
        ),
    ]
