# Generated by Django 4.1.5 on 2023-05-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ayurveda", "0015_token_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token_booking",
            name="number",
            field=models.IntegerField(default=0),
        ),
    ]
