# Generated by Django 4.1.5 on 2023-05-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ayurveda", "0016_alter_token_booking_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="token_booking",
            name="created_at",
        ),
        migrations.AddField(
            model_name="token_booking",
            name="appointment_time",
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
