# Generated by Django 4.1.5 on 2023-05-28 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ayurveda", "0017_remove_token_booking_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package_Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_name", models.CharField(max_length=500)),
                ("package_duration", models.CharField(max_length=500)),
                ("package_price", models.CharField(max_length=500)),
                ("booking_date", models.DateField()),
                ("booking_status", models.CharField(max_length=10)),
                ("package_photo", models.ImageField(upload_to="images")),
                (
                    "packages",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.packages",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Treatments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patientname", models.CharField(blank=True, max_length=50, null=True)),
                ("doctorname", models.CharField(max_length=20)),
                ("disease", models.CharField(max_length=200)),
                ("medicine", models.CharField(max_length=500)),
                ("treatment_date", models.DateField()),
                ("treatment_status", models.CharField(max_length=10)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.patient",
                    ),
                ),
                (
                    "token_booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.token_booking",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Package_payment_tb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "package_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("package_price", models.IntegerField()),
                ("payment_date", models.DateField()),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "Package_Booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.package_books",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.patient",
                    ),
                ),
            ],
        ),
    ]
