# Generated by Django 4.1.5 on 2023-05-27 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ayurveda", "0017_remove_token_booking_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package_Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package_name", models.CharField(max_length=500)),
                ("package_duration", models.CharField(max_length=500)),
                ("package_price", models.CharField(max_length=500)),
                ("booking_status", models.CharField(max_length=10)),
                ("package_photo", models.ImageField(upload_to="images")),
                (
                    "packages",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.packages",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Package_payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "package_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("package_price", models.IntegerField()),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "package_booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.package_booking",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medicine_orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medicine_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "medicine_qnty",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("medicine_price", models.IntegerField()),
                (
                    "medicine_photo",
                    models.ImageField(blank=True, null=True, upload_to="images"),
                ),
                (
                    "order_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.medicine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medicine_Carts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("medicine_name", models.CharField(max_length=500)),
                ("medicine_qnty", models.CharField(max_length=500)),
                ("medicine_price", models.CharField(max_length=500)),
                ("cart_status", models.CharField(max_length=10)),
                ("medicine_photo", models.ImageField(upload_to="images")),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.medicine",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.patient",
                    ),
                ),
            ],
        ),
    ]
