# Generated by Django 4.1.5 on 2023-05-31 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ayurveda", "0019_cart"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="treatments",
            name="patient",
        ),
    ]
