# Generated by Django 4.1.5 on 2023-06-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ayurveda", "0020_remove_treatments_patient"),
    ]

    operations = [
        migrations.CreateModel(
            name="payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.CharField(max_length=10)),
                ("date", models.DateField()),
                ("paymentstatus", models.CharField(default="0", max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medicine_name",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "medicine_qnty",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("medicine_price", models.IntegerField()),
                (
                    "medicine_photo",
                    models.ImageField(blank=True, null=True, upload_to="images"),
                ),
                (
                    "order_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.medicine",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ayurveda.patient",
                    ),
                ),
            ],
        ),
    ]
